# Exercício

- Classifique cada coluna do dataset a seguir como nominal, ordinal, binária, discreta ou contínua, com base apenas na descrição do dicionário de dados
- Com auxílio do método de dataframes `describe`, confirme sua classificação anterior
- Remova colunas com valor constante
- Crie as seguintes listas Python com os nomes das colunas que encaixam na descrição sugerida pelo nome da lista
  - `colunas_categoricas_nao_ordenadas`
  - `colunas_categoricas_ordenadas`
  - `coluna_alvo`
  - `colunas_numericas`
- Com as listas criadas, transforme as colunas categóricas do dataframe em tipo `category`, tomando cuidado de considerar se são ordenadas ou não. Ou seja, as categóricas ordenadas devem ser criadas considerando a ordem natural de seus elementos.
- Crie uma única figura com os histogramas de todas as colunas numéricas

## O dataset

O dataset a ser utilizado é o *IBM HR Analytics Employee Attrition & Performance*, disponível no Kaggle. O dataset contém informações sobre funcionários de uma empresa fictícia, como idade, gênero, estado civil, nível de satisfação, entre outros. O objetivo é prever a probabilidade de um funcionário sair da empresa.

[Link do Kaggle](https://www.kaggle.com/datasets/pavansubhasht/ibm-hr-analytics-attrition-dataset/data)

Os termos *attrition* ("atrito") e *turnover* ("rotatividade") são frequentemente usados de forma intercambiável no contexto de recursos humanos e gestão de força de trabalho, mas eles se referem a conceitos ligeiramente diferentes em relação às mudanças no número e na composição dos empregados dentro de uma organização. Compreender a distinção entre esses dois é importante para analisar e relatar com precisão a dinâmica da força de trabalho.

### Atrito

Atrito refere-se à redução gradual de empregados por meio de circunstâncias naturais, como aposentadoria, demissão voluntária por motivos pessoais, ou a decisão de não substituir empregados que estão de saída. Atrito pode levar a uma diminuição no tamanho da força de trabalho, mas é caracterizado por sua natureza voluntária e muitas vezes incontrolável. Organizações podem permitir o atrito para reduzir o tamanho de sua força de trabalho sem recorrer a demissões, vendo isso como uma forma menos disruptiva de ajustar seus níveis de pessoal.

Em análises, quando você está analisando um conjunto de dados para atrito, você frequentemente olha para as razões por trás das saídas voluntárias e a taxa na qual estas ocorrem naturalmente ao longo do tempo. Taxas de atrito podem fornecer insights sobre a satisfação dos empregados e tendências de longo prazo da força de trabalho.

### Rotatividade

Rotatividade, por outro lado, engloba um escopo mais amplo de partidas de empregados, incluindo tanto renúncias voluntárias quanto demissões involuntárias (como demissões ou términos por justa causa). Porém, ocorre a substituição da força de trabalho. Rotatividade é uma medida de quantos empregados estão deixando a companhia por qualquer motivo. Uma alta taxa de rotatividade pode indicar problemas com satisfação no trabalho, cultura do local de trabalho, ou estabilidade organizacional, e frequentemente requer ação da gestão para endereçar as causas subjacentes.

Rotatividade é calculada dividindo o número de empregados que saem pelo número médio de empregados, geralmente em uma base anual, e expressando isso como uma porcentagem. Esta métrica é crucial para entender como as saídas de empregados, tanto voluntárias quanto involuntárias, afetam a capacidade da organização de manter uma força de trabalho estável e eficaz.

### Diferenças Chave

- **Natureza**: Atrito geralmente é voluntário e pode ser devido a fatores naturais ou incontroláveis, enquanto rotatividade inclui tanto saídas voluntárias quanto demissões involuntárias.
- **Implicações para Gestão**: Atrito pode ser parte de uma estratégia de ajuste natural da força de trabalho e nem sempre é negativo, enquanto alta rotatividade é frequentemente um sinal de problemas dentro da organização que precisam ser abordados.
- **Foco Estratégico**: Análise de atrito pode focar em entender tendências de longo prazo da força de trabalho e planejamento de aposentadoria, enquanto análise de rotatividade é frequentemente usada para identificar questões imediatas com satisfação de empregados, engajamento, ou práticas de gestão que podem estar impactando a retenção de staff.

Enquanto ambos atrito e rotatividade lidam com empregados deixando a organização, eles diferem em seu escopo e as implicações estratégicas para gerenciar e entender a dinâmica da força de trabalho. No seu conjunto de dados de empregados, distinguir entre atrito e rotatividade pode ajudar na customização de estratégias para planejamento da força de trabalho, retenção e desenvolvimento organizacional.

|    | Name                       | Description                                                                                                                                                    |
|---:|:---------------------------|:---------------------------------------------------------------------------------------------------------------------------------------------------------------|
|  0 | Age                        | Numerical Value                                                                                                                                                |
|  1 | Attrition                  | Employee leaving the company - Text - No, Yes                                                                                                                     |
|  2 | BusinessTravel            | Text - Non-Travel, Travel_Frequently, Travel_Rarely                                                                                                             |
|  3 | DailyRate                 | Numerical Value - Salary Level                                                                                                                                 |
|  4 | Department                 | Text - Sales, Research & Development, Human Resources                                                                                                         |
|  5 | DistanceFromHome         | Numerical Value - the distance from work to home in miles 
|  6 | Education                  | Numerical Value - 1=Below college, 2=College, 3=Bachelor, 4=Master, 5=PhD   |
|  7 | EducationField            | Text - Life Sciences, Medical, Marketing, Techincal Degree, Human Resources, Other                                                                                   |
|  8 | EmployeeCount             | Numerical Value - 1                                                                                                                                               |
|  9 | EmployeeNumber            | Numerical Value - Employee ID                                                                                                                                  |
| 10 | EnvironmentSatisfaction    | Numerical Value - 1=Low, 2=Medium, 3=High, 4=Very High |
| 11 | Gender                     | Text - Female, Male                                                                                                                                             |
| 12 | HourlyRate                | Numerical Value - Hourly Salary                                                                                                                                |
| 13 | JobInvolvement            | Numerical Value - 1=Low, 2=Medium, 3=High, 4=Very High                                                                                                         |
| 14 | JobLevel                  | Numerical Value - 1, 2, 3, 4, 5. Means different job levels                                                                                                     |
| 15 | JobRole                   | Text - Sales Executive, Research Scientist, Laboratory Technician, Manufacturing Director, Healthcare Representative, Manager, Sales Representative, Research Director, Human Resources |
| 16 | JobSatisfaction           | Numerical Value - 1=Low, 2=Medium, 3=High, 4=Very High                                                                                                         |
| 17 | MaritalStatus             | Text - Single, Married, Divorced                                                                                                                                      |
| 18 | MonthlyIncome             | Numerical Value - Monthly Salary                                                                                                                               |
| 19 | MonthlyRate                | Numerical Value - Monthly Rate                                                                                                                                  |
| 20 | NumCompaniesWorked        | Numerical Value - Number of companies worked at                                                                                                                |
| 21 | Over18                    | Text - Y                                                                                                                                                    |
| 22 | Overtime                   | Text - No, Yes                                                                                                                                                    |
| 23 | PercentSalaryHike        | Numerical Value - Percentage increase in salary                                                                                                                |
| 24 | PerformanceRating         | Numerical Value - 1=Low, 2=Good, 3=Excellent, 4=Outstanding                                                                                                    |
| 25 | RelationshipSatisfaction  | Numerical Value - 1=Low, 2=Medium, 3=High, 4=Very High                                                                                                         |
| 26 | StandardHours             | Numerical Value - 80                                                                                                                                            |
| 27 | StockOptionsLevel        | Numerical Value - 0, 1, 2, 3                                                                                                                                    |
| 28 | TotalWorkingYears        | Numerical Value - Total years worked                                                                                                                            |
| 29 | TrainingTimesLastYear   | Numerical Value - How many times the employee has been trained last year                                                                                       |
| 30 | WorkLifeBalance          | Numerical Value - 1=Bad, 2=Good, 3=Better, 4=Best                                                                                                              |
| 31 | YearsAtCompany           | Numerical Value - Number of years at the company                                                                                                                |
| 32 | YearsInCurrentRole      | Numerical Value -Number of years in current role                                                                                                                |
| 33 | YearsSinceLastPromotion | Numerical Value - Years since last promotion                                                                                                                    |
| 34 | YearsWithCurrManager | Numerical Value - Years with current manager                                                                                                                    |

## Código

In [1]:
import pandas as pd

DADOS = "dados/employee_attrition.csv"

df = pd.read_csv(DADOS)
print(df.columns)
print('\n\n')
print(df.info())
# print('\n\n')
# print(df.head())

Index(['Age', 'Attrition', 'BusinessTravel', 'DailyRate', 'Department',
       'DistanceFromHome', 'Education', 'EducationField', 'EmployeeCount',
       'EmployeeNumber', 'EnvironmentSatisfaction', 'Gender', 'HourlyRate',
       'JobInvolvement', 'JobLevel', 'JobRole', 'JobSatisfaction',
       'MaritalStatus', 'MonthlyIncome', 'MonthlyRate', 'NumCompaniesWorked',
       'Over18', 'OverTime', 'PercentSalaryHike', 'PerformanceRating',
       'RelationshipSatisfaction', 'StandardHours', 'StockOptionLevel',
       'TotalWorkingYears', 'TrainingTimesLastYear', 'WorkLifeBalance',
       'YearsAtCompany', 'YearsInCurrentRole', 'YearsSinceLastPromotion',
       'YearsWithCurrManager'],
      dtype='object')



<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1470 entries, 0 to 1469
Data columns (total 35 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   Age                       1470 non-null   int64
 1   Attrition                 1470 non-null   object
 2   BusinessTravel            1470 non-null   object
 3   DailyRate                 1470 non-null   int64
 4   Department                1470 non-null   object
 5   DistanceFromHome          1470 non-null   int64
 6   Education                 1470 non-null   int64
 7   EducationField            1470 non-null   object
 8   EmployeeCount             1470 non-null   int64
 9   EmployeeNumber            1470 non-null   int64
 10  EnvironmentSatisfaction   1470 non-null   int64
 11  Gender                    1470 non-null   object
 12  HourlyRate                1470 non-null   int64
 13  JobInvolvement            1470 non-null   int64
 14  JobLevel                  1470 non-null   int64
 15  JobRole                   1470 non-null   object
 16  JobSatisfaction           1470 non-null   int64
 17  MaritalStatus             1470 non-null   object
 18  MonthlyIncome             1470 non-null   int64
 19  MonthlyRate               1470 non-null   int64
 20  NumCompaniesWorked        1470 non-null   int64
 21  Over18                    1470 non-null   object
 22  OverTime                  1470 non-null   object
 23  PercentSalaryHike         1470 non-null   int64
 24  PerformanceRating         1470 non-null   int64
 25  RelationshipSatisfaction  1470 non-null   int64
 26  StandardHours             1470 non-null   int64
 27  StockOptionLevel          1470 non-null   int64
 28  TotalWorkingYears         1470 non-null   int64
 29  TrainingTimesLastYear     1470 non-null   int64
 30  WorkLifeBalance           1470 non-null   int64
 31  YearsAtCompany            1470 non-null   int64
 32  YearsInCurrentRole        1470 non-null   int64
 33  YearsSinceLastPromotion   1470 non-null   int64
 34  YearsWithCurrManager      1470 non-null   int64
dtypes: int64(26), object(9)
memory usage: 402.1+ KB
None

 0   Age                       quantitativa discreta\
 1   Attrition                 qualitativa binária\
 2   BusinessTravel            qualitativa nominal\
 3   DailyRate                 quantitativa contínua\
 4   Department                qualitativa nominal\
 5   DistanceFromHome          quantitativa contínua/discreta\
 6   Education                 qualitativa ordinária\
 7   EducationField            qualitativa nominal\
 8   EmployeeCount             quantitativa discreta\
 9   EmployeeNumber            quantitativa discreta\
 10  EnvironmentSatisfaction   qualitativa ordinária\
 11  Gender                    qualitativa binária\
 12  HourlyRate                quantitativa contínua\
 13  JobInvolvement            qualitativa ordinária\
 14  JobLevel                  qualitativa ordinária\
 15  JobRole                   qualitativa nominal\
 16  JobSatisfaction           quantitativa discreta\
 17  MaritalStatus             qualitativa nominal\
 18  MonthlyIncome             quantitativa contínua\
 19  MonthlyRate               quantitativa contínua\
 20  NumCompaniesWorked        quantitativa discreta\
 21  Over18                    qualitativa binária\
 22  OverTime                  qualitativa binária\
 23  PercentSalaryHike         quantitativa contínua\
 24  PerformanceRating         qualitativa ordinária\
 25  RelationshipSatisfaction  qualitativa ordinária\
 26  StandardHours             quantitativa discreta\
 27  StockOptionLevel          qualitativa ordinária\
 28  TotalWorkingYears         quantitativa discreta\
 29  TrainingTimesLastYear     quantitativa discreta\
 30  WorkLifeBalance           qualitativa ordinária\
 31  YearsAtCompany            quantitativa discreta\
 32  YearsInCurrentRole        quantitativa discreta\
 33  YearsSinceLastPromotion   quantitativa discreta\
 34  YearsWithCurrManager      quantitativa discreta

In [2]:
with pd.option_context('display.max_columns', 33):
    display(df.head())

,Age,Attrition,BusinessTravel,DailyRate,Department,DistanceFromHome,Education,EducationField,EmployeeCount,EmployeeNumber,EnvironmentSatisfaction,Gender,HourlyRate,JobInvolvement,JobLevel,JobRole,...,MonthlyRate,NumCompaniesWorked,Over18,OverTime,PercentSalaryHike,PerformanceRating,RelationshipSatisfaction,StandardHours,StockOptionLevel,TotalWorkingYears,TrainingTimesLastYear,WorkLifeBalance,YearsAtCompany,YearsInCurrentRole,YearsSinceLastPromotion,YearsWithCurrManager
0,41,Yes,Travel_Rarely,1102,Sales,1,2,Life Sciences,1,1,2,Female,94,3,2,Sales Executive,...,19479,8,Y,Yes,11,3,1,80,0,8,0,1,6,4,0,5
1,49,No,Travel_Frequently,279,Research & Development,8,1,Life Sciences,1,2,3,Male,61,2,2,Research Scientist,...,24907,1,Y,No,23,4,4,80,1,10,3,3,10,7,1,7
2,37,Yes,Travel_Rarely,1373,Research & Development,2,2,Other,1,4,4,Male,92,2,1,Laboratory Technician,...,2396,6,Y,Yes,15,3,2,80,0,7,3,3,0,0,0,0
3,33,No,Travel_Frequently,1392,Research & Development,3,4,Life Sciences,1,5,4,Female,56,3,1,Research Scientist,...,23159,1,Y,Yes,11,3,3,80,0,8,3,3,8,7,3,0
4,27,No,Travel_Rarely,591,Research & Development,2,1,Medical,1,7,1,Male,40,3,1,Laboratory Technician,...,16632,9,Y,No,12,3,4,80,1,6,3,3,2,2,2,2

In [3]:
with pd.option_context('display.max_columns', 33):
    display(df.describe(exclude='number'))

,Attrition,BusinessTravel,Department,EducationField,Gender,JobRole,MaritalStatus,Over18,OverTime
count,1470,1470,1470,1470,1470,1470,1470,1470,1470
unique,2,3,3,6,2,9,3,1,2
top,No,Travel_Rarely,Research & Development,Life Sciences,Male,Sales Executive,Married,Y,No
freq,1233,1043,961,606,882,326,673,1470,1054

## Código

#### 1) Removendo colunas com valores constantes

In [4]:
print(len(df.columns))
df.drop(['Over18', 'EmployeeCount', 'StandardHours', 'EmployeeNumber'], axis=1, inplace=True)
print(len(df.columns))

35
31

## Criando as listas das colunas

In [5]:
colunas_categoricas_nao_ordenadas = ['BusinessTravel', 'Department', 'EducationField', 'Gender',
                                    'JobRole', 'MaritalStatus', 'OverTime']
colunas_categoricas_ordenadas = ['Education', 'EnvironmentSatisfaction', 'JobSatisfaction', 'JobInvolvement',
                                 'JobLevel', 'PerformanceRating', 'RelationshipSatisfaction', 'StockOptionLevel',
                                 'WorkLifeBalance']
coluna_alvo = ['Attrition']
colunas_numericas = [ col for col in df.columns if col not in (colunas_categoricas_nao_ordenadas +
                                                              colunas_categoricas_ordenadas +
                                                              coluna_alvo)
                     ]

In [6]:
colunas_numericas

['Age',
 'DailyRate',
 'DistanceFromHome',
 'HourlyRate',
 'MonthlyIncome',
 'MonthlyRate',
 'NumCompaniesWorked',
 'PercentSalaryHike',
 'TotalWorkingYears',
 'TrainingTimesLastYear',
 'YearsAtCompany',
 'YearsInCurrentRole',
 'YearsSinceLastPromotion',
 'YearsWithCurrManager']

In [7]:
for col in colunas_categoricas_nao_ordenadas:
    df[col] = df[col].astype('category')
    
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1470 entries, 0 to 1469
Data columns (total 31 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   Age                       1470 non-null   int64
 1   Attrition                 1470 non-null   object
 2   BusinessTravel            1470 non-null   category
 3   DailyRate                 1470 non-null   int64
 4   Department                1470 non-null   category
 5   DistanceFromHome          1470 non-null   int64
 6   Education                 1470 non-null   int64
 7   EducationField            1470 non-null   category
 8   EnvironmentSatisfaction   1470 non-null   int64
 9   Gender                    1470 non-null   category
 10  HourlyRate                1470 non-null   int64
 11  JobInvolvement            1470 non-null   int64
 12  JobLevel                  1470 non-null   int64
 13  JobRole                   1470 non-null   category
 14  JobSatisfaction           1470 non-null   int64
 15  MaritalStatus             1470 non-null   category
 16  MonthlyIncome             1470 non-null   int64
 17  MonthlyRate               1470 non-null   int64
 18  NumCompaniesWorked        1470 non-null   int64
 19  OverTime                  1470 non-null   category
 20  PercentSalaryHike         1470 non-null   int64
 21  PerformanceRating         1470 non-null   int64
 22  RelationshipSatisfaction  1470 non-null   int64
 23  StockOptionLevel          1470 non-null   int64
 24  TotalWorkingYears         1470 non-null   int64
 25  TrainingTimesLastYear     1470 non-null   int64
 26  WorkLifeBalance           1470 non-null   int64
 27  YearsAtCompany            1470 non-null   int64
 28  YearsInCurrentRole        1470 non-null   int64
 29  YearsSinceLastPromotion   1470 non-null   int64
 30  YearsWithCurrManager      1470 non-null   int64
dtypes: category(7), int64(23), object(1)
memory usage: 287.0+ KB

In [ ]:
classificacao = []
for col in df.columns:
    num_unique_values = df[col].nunique()
    print(f'Coluna do tipo {df[col].dtype}: {col} - Valores únicos: {num_unique_values}')
    
    if df[col].dtype == int:
        classificacao.append('discreta')
        
    elif df[col].dtype == float:
        classificacao.append('continua')
    
    elif df[col].dtype == object and num_unique_values == 2:
        classificacao.append('binária')
        
    elif df[col].dtype == object and num_unique_values > 2:
        classificacao.append('nominal')

In [ ]:
print(classificacao)