<img alt="Colaboratory logo" width="15%" src="https://raw.githubusercontent.com/carlosfab/escola-data-science/master/img/novo_logo_bg_claro.png">

#### **Data Science na Prática 3.0**
*by [sigmoidal.ai](https://sigmoidal.ai)*

---

# Análise dos Dados do Airbnb - *Sua Cidade*

O [Airbnb](https://www.airbnb.com.br/) já é considerado como sendo a **maior empresa hoteleira da atualidade**. Ah, o detalhe é que ele **não possui nenhum hotel**!

Conectando pessoas que querem viajar (e se hospedar) com anfitriões que querem alugar seus imóveis de maneira prática, o Airbnb fornece uma plataforma inovadora para tornar essa hospedagem alternativa.

No final de 2018, a Startup fundada 10 anos atrás, já havia **hospedado mais de 300 milhões** de pessoas ao redor de todo o mundo, desafiando as redes hoteleiras tradicionais.

Uma das iniciativas do Airbnb é disponibilizar dados do site, para algumas das principais cidades do mundo. Por meio do portal [Inside Airbnb](http://insideairbnb.com/get-the-data.html), é possível baixar uma grande quantidade de dados para desenvolver projetos e soluções de *Data Science*.

<center><img alt="Analisando Airbnb" width="10%" src="https://www.area360.com.au/wp-content/uploads/2017/09/airbnb-logo.jpg"></center>

**Neste *notebook*, iremos analisar os dados referentes à cidade ________, e ver quais insights podem ser extraídos a partir de dados brutos.**

## Obtenção dos Dados

In [1]:
# importar os pacotes necessarios
import pandas as pd # importando o pacote que lê os dados do Airbnb

In [2]:
from google.colab import drive
drive.mount('/content/drive') # montando o drive contendo os dados utilizados

Mounted at /content/drive

In [3]:
# importar o arquivo listings.csv para um DataFrame
df = pd.read_csv("drive/MyDrive/London/london_listings.csv") # lendo o arquivo csv contendo os dados utilizados

## Análise dos Dados

Os dados da plataforma Airbnb referentes à cidade de Londres (London) foram utilizados nas análise subsequentes. Inicialmente vemos uma base de dados que comporta 66640 linhas e 18 colunas (veja a seguir). As colunas serão descritas na seção de dicionário de variáveis.

In [4]:
print(df.shape)
print(df.columns)

(66640, 18)
Index(['id', 'name', 'host_id', 'host_name', 'neighbourhood_group',
       'neighbourhood', 'latitude', 'longitude', 'room_type', 'price',
       'minimum_nights', 'number_of_reviews', 'last_review',
       'reviews_per_month', 'calculated_host_listings_count',
       'availability_365', 'number_of_reviews_ltm', 'license'],
      dtype='object')

**Dicionário das variáveis**

* id - Número de ID do Anúncio
* name - Título do Anúncio
* host_id - Número de ID do Host
* host_name - Nome do Host
* neighbourhood_group -
* neighbourhood - Nome do Bairro
* latitude - Coordenadas de Latitude
* longitude - Coordenadas de Longitude
* room_type - Tipo de Hospedagem
* price - Valor da Diária
* minimum_nights - Número mínimo de Noites de Hospedagem
* number_of_reviews - Número de reviews dados pelos hóspedes
* last_review - Data do último review
* reviews_per_month - Porcentagem de reviews por mês
* calculated_host_listings_count - Número de lugares para alugar
* availability_365 - Disponibilidade durante o ano
* number_of_reviews_ltm - 
* license - Licença

Antes de iniciar qualquer análise, vamos verificar a cara do nosso *dataset*, analisando as 5 primeiras entradas.

In [5]:
# mostrar as 5 primeiras entradas
df.head()

,id,name,host_id,host_name,neighbourhood_group,neighbourhood,latitude,longitude,room_type,price,minimum_nights,number_of_reviews,last_review,reviews_per_month,calculated_host_listings_count,availability_365,number_of_reviews_ltm,license
0,36299,Kew Gardens 3BR house in cul-de-sac,155938,Geert,NaN,Richmond upon Thames,51.48085,-0.28086,Entire home/apt,195,3,89,2022-03-07,0.64,1,233,10,NaN
1,15400,Bright Chelsea Apartment. Chelsea!,60302,Philippa,NaN,Kensington and Chelsea,51.48780,-0.16813,Entire home/apt,75,3,89,2020-03-16,0.60,1,9,0,NaN
2,17402,Superb 3-Bed/2 Bath & Wifi: Trendy W1,67564,Liz,NaN,Westminster,51.52195,-0.14094,Entire home/apt,307,4,45,2022-01-17,0.34,1,213,3,NaN
3,36660,You are GUARANTEED to love this,157884,Agri & Roger,NaN,Haringey,51.58478,-0.16057,Private room,72,2,550,2022-03-01,3.93,2,236,22,NaN
4,17506,Boutique Chelsea/Fulham Double bed 5-star ensuite,67915,Charlotte,NaN,Hammersmith and Fulham,51.47935,-0.19743,Private room,150,3,0,NaN,NaN,2,364,0,NaN

### **Q1. Quantos atributos (variáveis) e quantas entradas o nosso conjunto de dados possui? Quais os tipos das variáveis?**

In [6]:
# identificar o volume de dados do DataFrame
print(df.shape)
# verificar as 5 primeiras entradas do dataset
df.head()

(66640, 18)

,id,name,host_id,host_name,neighbourhood_group,neighbourhood,latitude,longitude,room_type,price,minimum_nights,number_of_reviews,last_review,reviews_per_month,calculated_host_listings_count,availability_365,number_of_reviews_ltm,license
0,36299,Kew Gardens 3BR house in cul-de-sac,155938,Geert,NaN,Richmond upon Thames,51.48085,-0.28086,Entire home/apt,195,3,89,2022-03-07,0.64,1,233,10,NaN
1,15400,Bright Chelsea Apartment. Chelsea!,60302,Philippa,NaN,Kensington and Chelsea,51.48780,-0.16813,Entire home/apt,75,3,89,2020-03-16,0.60,1,9,0,NaN
2,17402,Superb 3-Bed/2 Bath & Wifi: Trendy W1,67564,Liz,NaN,Westminster,51.52195,-0.14094,Entire home/apt,307,4,45,2022-01-17,0.34,1,213,3,NaN
3,36660,You are GUARANTEED to love this,157884,Agri & Roger,NaN,Haringey,51.58478,-0.16057,Private room,72,2,550,2022-03-01,3.93,2,236,22,NaN
4,17506,Boutique Chelsea/Fulham Double bed 5-star ensuite,67915,Charlotte,NaN,Hammersmith and Fulham,51.47935,-0.19743,Private room,150,3,0,NaN,NaN,2,364,0,NaN

### **Q2. Qual a porcentagem de valores ausentes no *dataset*?**

In [ ]:
# ordenar em ordem decrescente as variáveis por seus valores ausentes

### **Q3. Qual o tipo de distribuição das variáveis?**

In [ ]:
# plotar o histograma das variáveis numéricas

### **Q4. Qual a média dos preços de aluguel?**

In [ ]:
# ver a média da coluna `price``

### **Q4. Qual a correlação existente entre as variáveis**

In [ ]:
# criar uma matriz de correlação

# mostrar a matriz de correlação

In [ ]:
# plotar um heatmap a partir das correlações

### **Q5. Qual o tipo de imóvel mais alugado no Airbnb?**

In [ ]:
# mostrar a quantidade de cada tipo de imóvel disponível

In [ ]:
# mostrar a porcentagem de cada tipo de imóvel disponível

### **Q6. Qual a localidade mais cara do dataset?**

In [ ]:
# ver preços por bairros, na média

In [ ]:
# plotar os imóveis pela latitude-longitude

### **Q7. Qual é a média do mínimo de noites para aluguel (minimum_nights)?**

In [ ]:
# ver a média da coluna `minimum_nights``

## Conclusões